plugins:
    security:
        ssl:
            transport:
                pemcert_filepath: certs/indexer.pem
                pemkey_filepath: certs/indexer-key.pem
                pemtrustedcas_filepath: certs/root-ca.pem
                enforce_hostname_verification: false
            http:
                enabled: true
                pemcert_filepath: certs/indexer.pem
                pemkey_filepath: certs/indexer-key.pem
                pemtrustedcas_filepath: certs/root-ca.pem
        allow_unsafe_democertificates: true
        allow_default_init_securityindex: true
        authcz:
            admin_dn:
                - CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
        audit:
            type: internal_opensearch
        enable_snapshot_restore_privilege: true
        check_snapshot_restore_write_privileges: true
        restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
        system_indices:
            enabled: true
            indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]
